export enum UserRole {
    REGISTERED_USER = 'REGISTERED_USER',
    BROKER = 'BROKER',
    SELLERS = 'SELLERS',
    REALITY_DEVELOPER = 'REALITY_DEVELOPER',
    ADMINISTRATOR = 'ADMINISTRATOR',
    MODERATOR = 'MODERATOR',
    PHOTOGRAPHER = 'PHOTOGRAPHER',
    SUPER_ADMIN = 'SUPER_ADMIN',
    CONTENT_CREATOR = 'CONTENT_CREATOR',
    BLOGGER = 'BLOGGER',
    TECHNICAL_SUPPORT = 'TECHNICAL_SUPPORT',
  }