/** DEFAULT DATE AND TIME FORMAT FOR END POINTS */
export const GLOBAL_DATE_TIME_FORMATE = 'YYYY-MM-dd hh:mm:ss';

/** DEFAULT DATE FORMAT FOR END POINTS */
export const GLOBAL_DATE_FORMATE = 'dd/MM/YYYY';

/** DATE NAME FORMAT */
export const DATE_NAME_FORMATE = 'MMMM YYYY';
export const DATE_MONTH_YEAR_FORMATE = 'MMM YYYY';

/** DEFAULT TIME FORMAT FOR END POINTS */
export const GLOBAL_TIME_FORMATE = 'HH:mm';

/** DEFAULT TIME FORMAT FOR END POINTS WITH SECONDS */
export const GLOBAL_TIME_FORMATE_SEC = 'HH:mm:ss';

/** 12 HOUR FORMATE - DEFAULT TIME FORMAT FOR END POINTS WITH SECONDS */
export const GLOBAL_TIME_FORMATE_SEC_12_HOUR = 'hh:mm:ss a';

/** DEFAULT TIME FORMAT FOR END POINTS */
export const MERIDIAN_TIME_FORMATE = 'hh:mm a';

/** DEFAULT DATE MONTH FORMAT */
export const GLOBAL_DAY_MONTH_FORMATE = 'DD MMM';

/** DATE FORMAT 18 NOV 2020 */
export const GLOBAL_DATE_FORMAT_DD_MMM = 'DD MMM YYYY';

/** DATE FORMAT 18 NOV 20 */
export const GLOBAL_DATE_FORMAT_DD_MMM_YY = 'DD MMM YY';

/** REQUEST DATA FORMAT */
export const REQUEST_DATE_FORMAT = 'YYYY-MM-DD';

/** FRIDAY, JUL 17, 2020 */
export const FULL_DATE = 'dddd, ll';

/**  TABLE DATE TRANSFORM */
export const GLOBAL_TABLE_TIME_FORMATE = 'dd-MM-yyyy hh:mm a';

/**  ON UPDATE FORM FORMATE */
export const FORM_DATE_FORMATE_ORIGINAL = 'DD-MM-YYYY h:mm A';
export const FORM_DATE_TIME_FORMATE = 'YYYY-MM-ddTHH:mm:ss.SSSZ';
export const FORM_DATE_TIME_FORMATE_WITHOUT_ZONE = 'YYYY-MM-ddTHH:mm:ss';
export const FORM_DATE_FORMATE = 'YYYY-MM-dd';
export const FORM_TIME_FORMATE = 'HH:mm:ss';
export const FORM_DATETIME_FORMATE = 'dd-MM-YYYYTHH:mm:ss';
